DROP TABLE IF EXISTS video;

CREATE TABLE video (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(100) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO
    video(titulo, descricao, url)
VALUES
    (
        'Dropei 30 e perdi',
        'Dropando 30 boneco e perdendo a partida pq só tem noob no meu time',
        'https://www.youtube.com/watch?v=1SQKgih9fY8&ab_channel=VISKFPS'
    )